language: node_js
node_js:
  - "12"
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
script:
  
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master